- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:          
     - include: tasks/packages.yml
     #These YAML files can be run to set up a user to 
     #execute a cron job to watch for ansible changes
     #   - include: tasks/users.yml 
     #   - include: tasks/cron.yml
